# Generated by Django 3.0.4 on 2020-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200319_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDeliveryAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_agree', models.BooleanField()),
            ],
        ),
    ]
