# Generated by Django 3.0.4 on 2020-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_maildeliveryagree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailDeliveryAgree',
        ),
        migrations.AddField(
            model_name='profile',
            name='check_agree',
            field=models.BooleanField(null=True),
        ),
    ]
