# Generated by Django 3.0.4 on 2020-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200319_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='check_agree',
            field=models.BooleanField(default=True),
        ),
    ]
