# Generated by Django 3.0.4 on 2020-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200319_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='check_agree',
            field=models.BooleanField(default=True, verbose_name='Согланешие об отправке уведомлений на электронную почту'),
        ),
    ]
