# Generated by Django 3.0.4 on 2020-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200320_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужской '), ('2', 'Женский')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
